### PR TITLE
first draft of an English version, closes #1

### LINKED ISSUE #1: English version?
I would like to work at an English version of this. Ideally i would like to use English as the main language, but if you want we can keep an Italian README and an English README

### PR DESCRIPTION
**Pull request by danse**

### CODE REVIEW

**Comment by sic2** [comment]
@danse,
@vigliag  and I will look into this. 
It looks good, but we have been discussing a lot about what the best solution is. Our idea is to avoid duplication as much as possible.

We will get back to you soon. 

ps. we will use your translation in whatever case. Thanks a lot!

**Comment by danse** [comment]
Alright, this was just a draft, there could be broken links and the like

**Comment by vigliag** [comment]
I merged in your translation (thanks a lot, it is great), but I edited the page so it links back to the original list instead of duplicating it. We'll decide what to do with the groups which may be interesting for tourists or foreigners later on, when we have more of them :)

**Comment by danse** [comment]
fair enough, nice idea :+1:

**Pull request merged**
